
name: plantpulse
description: Plant health monitoring application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  cached_network_image:
  cloud_firestore: ^4.8.0
  collection: ^1.16.0
  equatable: ^2.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.0
  firebase_database: ^10.2.2
  firebase_messaging: ^14.6.2
  fl_chart: ^0.62.0
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.4.0
  flutter_form_builder: ^9.0.0
  formz:
    path: ./dependencies/formz-0.4.1/
  getwidget: ^3.1.1
  geolocator: ^9.0.2
  google_sign_in: ^6.1.3
  intl: ^0.18.1
  page_transition: ^2.0.9
  pedantic: ^1.11.1
  provider: ^6.0.5
  clean_calendar: ^1.1.0
  image_picker: ^0.8.7+5
  native_image_cropper: ^0.3.1
  #tflite_flutter_helper_plus: ^0.0.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
      git:
        url: https://github.com/filofan1/tflite_flutter_helper.git
        ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  logger: ^1.3.0
  image: ^3.2.2
  image_cropper: ^4.0.1
  wc_form_validators: ^1.0.0
  http: ^0.13.6
  sign_in_with_apple: ^4.3.0
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.3.0
  syncfusion_flutter_charts: ^21.2.9
  flutter_secure_storage: ^8.0.0
  location: ^4.4.0
  flutter_easyloading: ^3.0.5
  #wifi_scan: ^0.4.0+1
  flutter_bluetooth_serial: ^0.4.0
  bluetooth_enable_fork: ^0.1.6
  flutter_svg: ^2.0.7
  #used for dynamic screen sizes
  flutter_screenutil: ^5.5.3+2
  #to add Google Fonts
  google_fonts: ^4.0.4
  wifi_iot: ^0.3.18


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/model.tflite
    - assets/dict.txt

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular-webfont.ttf
