name: formz
description: A unified form representation in Dart which aims to simplify form representation and validation in a generic way.
repository: https://github.com/ChicagoFlutter/formz
issue_tracker: https://github.com/ChicagoFlutter/formz/issues
homepage: https://github.com/ChicagoFlutter/formz
documentation: https://github.com/ChicagoFlutter/formz

version: 0.4.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  coverage: ^1.6.3
